// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ObjectivesService.DataAccess.Models;

#nullable disable

namespace ObjectivesService.DataAccess.Migrations
{
    [DbContext(typeof(ObjectivesContext))]
    [Migration("20250128194322_AddStatusValueTable")]
    partial class AddStatusValueTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ObjectivesService.Domain.Entities.StatusValueEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("StatusValues");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Создана"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Приостановлена"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Не достигнута"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Достигнута"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
