services:
  objective-manager-front:
    build:
      context: ./ObjectiveManager.front
      dockerfile: ./Dockerfile
    depends_on:
      - objective-manager-api
    ports:
      - "3000:3000"

  objective-manager-api:
    build:
      context: ./ObjectiveManager.APIGateway
      dockerfile: ObjectiveManager.Api/Dockerfile
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_URLS=http://*:5000
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/Objectives/all"]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres:
    image: postgres:17.0
    restart: unless-stopped
    environment:
      POSTGRES_DB: "ObjectiveManagerDB"
      POSTGRES_USER:  ${POSTGRES_USER}
      POSTGRES_PASSWORD:  ${POSTGRES_PASSWORD}
      PGPORT: 5433
    volumes:
      - pgdb-data:/var/lib/postgresql/data

volumes:
  pgdb-data: