services:
  objective-manager-front:
    build:
      context: ./ObjectiveManager.front
      dockerfile: ./Dockerfile
    depends_on:
      - objective-manager-api
    ports:
      - "3000:3000"

  objective-manager-api:
    build:
      context: ./ObjectiveManager.APIGateway
      dockerfile: ObjectiveManager.Api/Dockerfile
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings:Postgres=Host=postgres;Port=5433;Database=ObjectiveManagerDB;Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};

    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/Objectives/all"]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres:
    image: postgres:17.0
    restart: unless-stopped
    environment:
      POSTGRES_USER:  ${POSTGRES_USER}
      POSTGRES_PASSWORD:  ${POSTGRES_PASSWORD}
      POSTGRES_MULTIPLE_DATABASES: "ObjectivesServiceDB", "AuthServiceDB"
      PGPORT: 5433
    volumes:
      - postgres-data:/var/lib/postgresql/postgresData
      - ./docker-postgresql-multiple-databases:/docker-entrypoint-initdb.d

volumes:
  postgres-data: