// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ObjectiveManager.DataAccess.Models;

#nullable disable

namespace ObjectiveManager.DataAccess.Migrations
{
    [DbContext(typeof(ObjectivesContext))]
    [Migration("20250113185650_AddObjectiveTables")]
    partial class AddObjectiveTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ObjectiveManager.Domain.Entities.ObjectiveEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("FinalDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("StatusId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.ToTable("Objectives");
                });

            modelBuilder.Entity("ObjectiveManager.Domain.Entities.ObjectiveStatusEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ObjectiveStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Создана"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Приостановлена"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Не достигнута"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Достигнута"
                        });
                });

            modelBuilder.Entity("ObjectiveManager.Domain.Entities.ObjectiveEntity", b =>
                {
                    b.HasOne("ObjectiveManager.Domain.Entities.ObjectiveStatusEntity", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Status");
                });
#pragma warning restore 612, 618
        }
    }
}
