/* tslint:disable */
/* eslint-disable */
/**
 * ObjectiveManager.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ObjectiveStatus = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3
} as const;
export type ObjectiveStatus = typeof ObjectiveStatus[keyof typeof ObjectiveStatus];


export function instanceOfObjectiveStatus(value: any): boolean {
    for (const key in ObjectiveStatus) {
        if (Object.prototype.hasOwnProperty.call(ObjectiveStatus, key)) {
            if (ObjectiveStatus[key as keyof typeof ObjectiveStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ObjectiveStatusFromJSON(json: any): ObjectiveStatus {
    return ObjectiveStatusFromJSONTyped(json, false);
}

export function ObjectiveStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ObjectiveStatus {
    return json as ObjectiveStatus;
}

export function ObjectiveStatusToJSON(value?: ObjectiveStatus | null): any {
    return value as any;
}

export function ObjectiveStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): ObjectiveStatus {
    return value as ObjectiveStatus;
}

