/* tslint:disable */
/* eslint-disable */
/**
 * ObjectiveManager.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ObjectiveStatus } from './ObjectiveStatus';
import {
    ObjectiveStatusFromJSON,
    ObjectiveStatusFromJSONTyped,
    ObjectiveStatusToJSON,
} from './ObjectiveStatus';

/**
 * 
 * @export
 * @interface Objective
 */
export interface Objective {
    /**
     * 
     * @type {string}
     * @memberof Objective
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Objective
     */
    definition?: string | null;
    /**
     * 
     * @type {ObjectiveStatus}
     * @memberof Objective
     */
    status?: ObjectiveStatus;
    /**
     * 
     * @type {Date}
     * @memberof Objective
     */
    finalDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof Objective
     */
    comment?: string | null;
}



/**
 * Check if a given object implements the Objective interface.
 */
export function instanceOfObjective(value: object): value is Objective {
    return true;
}

export function ObjectiveFromJSON(json: any): Objective {
    return ObjectiveFromJSONTyped(json, false);
}

export function ObjectiveFromJSONTyped(json: any, ignoreDiscriminator: boolean): Objective {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'definition': json['definition'] == null ? undefined : json['definition'],
        'status': json['status'] == null ? undefined : ObjectiveStatusFromJSON(json['status']),
        'finalDate': json['finalDate'] == null ? undefined : (new Date(json['finalDate'])),
        'comment': json['comment'] == null ? undefined : json['comment'],
    };
}

export function ObjectiveToJSON(value?: Objective | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'definition': value['definition'],
        'status': ObjectiveStatusToJSON(value['status']),
        'finalDate': value['finalDate'] == null ? undefined : ((value['finalDate']).toISOString()),
        'comment': value['comment'],
    };
}

