/* tslint:disable */
/* eslint-disable */
/**
 * API Gateway
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountData
 */
export interface AccountData {
    /**
     * 
     * @type {string}
     * @memberof AccountData
     */
    userId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AccountData
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AccountData
     */
    surname?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AccountData
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AccountData
     */
    mentorEmail?: string | null;
}

/**
 * Check if a given object implements the AccountData interface.
 */
export function instanceOfAccountData(value: object): value is AccountData {
    return true;
}

export function AccountDataFromJSON(json: any): AccountData {
    return AccountDataFromJSONTyped(json, false);
}

export function AccountDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountData {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'] == null ? undefined : json['userId'],
        'name': json['name'] == null ? undefined : json['name'],
        'surname': json['surname'] == null ? undefined : json['surname'],
        'email': json['email'] == null ? undefined : json['email'],
        'mentorEmail': json['mentorEmail'] == null ? undefined : json['mentorEmail'],
    };
}

export function AccountDataToJSON(json: any): AccountData {
    return AccountDataToJSONTyped(json, false);
}

export function AccountDataToJSONTyped(value?: AccountData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'name': value['name'],
        'surname': value['surname'],
        'email': value['email'],
        'mentorEmail': value['mentorEmail'],
    };
}

