/* tslint:disable */
/* eslint-disable */
/**
 * API Gateway
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EditDataDto
 */
export interface EditDataDto {
    /**
     * 
     * @type {string}
     * @memberof EditDataDto
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EditDataDto
     */
    surname?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EditDataDto
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EditDataDto
     */
    mentorEmail?: string | null;
}

/**
 * Check if a given object implements the EditDataDto interface.
 */
export function instanceOfEditDataDto(value: object): value is EditDataDto {
    return true;
}

export function EditDataDtoFromJSON(json: any): EditDataDto {
    return EditDataDtoFromJSONTyped(json, false);
}

export function EditDataDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): EditDataDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'surname': json['surname'] == null ? undefined : json['surname'],
        'email': json['email'] == null ? undefined : json['email'],
        'mentorEmail': json['mentorEmail'] == null ? undefined : json['mentorEmail'],
    };
}

export function EditDataDtoToJSON(json: any): EditDataDto {
    return EditDataDtoToJSONTyped(json, false);
}

export function EditDataDtoToJSONTyped(value?: EditDataDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'surname': value['surname'],
        'email': value['email'],
        'mentorEmail': value['mentorEmail'],
    };
}

