/* tslint:disable */
/* eslint-disable */
/**
 * API Gateway
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EditAccountDto
 */
export interface EditAccountDto {
    /**
     * 
     * @type {string}
     * @memberof EditAccountDto
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EditAccountDto
     */
    surname?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EditAccountDto
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EditAccountDto
     */
    mentorEmail?: string | null;
}

/**
 * Check if a given object implements the EditAccountDto interface.
 */
export function instanceOfEditAccountDto(value: object): value is EditAccountDto {
    return true;
}

export function EditAccountDtoFromJSON(json: any): EditAccountDto {
    return EditAccountDtoFromJSONTyped(json, false);
}

export function EditAccountDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): EditAccountDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'surname': json['surname'] == null ? undefined : json['surname'],
        'email': json['email'] == null ? undefined : json['email'],
        'mentorEmail': json['mentorEmail'] == null ? undefined : json['mentorEmail'],
    };
}

export function EditAccountDtoToJSON(json: any): EditAccountDto {
    return EditAccountDtoToJSONTyped(json, false);
}

export function EditAccountDtoToJSONTyped(value?: EditAccountDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'surname': value['surname'],
        'email': value['email'],
        'mentorEmail': value['mentorEmail'],
    };
}

