/* tslint:disable */
/* eslint-disable */
/**
 * API Gateway
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FrequencyValueDTO
 */
export interface FrequencyValueDTO {
    /**
     * 
     * @type {number}
     * @memberof FrequencyValueDTO
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof FrequencyValueDTO
     */
    name?: string | null;
}

/**
 * Check if a given object implements the FrequencyValueDTO interface.
 */
export function instanceOfFrequencyValueDTO(value: object): value is FrequencyValueDTO {
    return true;
}

export function FrequencyValueDTOFromJSON(json: any): FrequencyValueDTO {
    return FrequencyValueDTOFromJSONTyped(json, false);
}

export function FrequencyValueDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): FrequencyValueDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function FrequencyValueDTOToJSON(json: any): FrequencyValueDTO {
    return FrequencyValueDTOToJSONTyped(json, false);
}

export function FrequencyValueDTOToJSONTyped(value?: FrequencyValueDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

