/* tslint:disable */
/* eslint-disable */
/**
 * API Gateway
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginViewModel
 */
export interface LoginViewModel {
    /**
     * 
     * @type {string}
     * @memberof LoginViewModel
     */
    email: string | null;
    /**
     * 
     * @type {string}
     * @memberof LoginViewModel
     */
    password: string | null;
}

/**
 * Check if a given object implements the LoginViewModel interface.
 */
export function instanceOfLoginViewModel(value: object): value is LoginViewModel {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function LoginViewModelFromJSON(json: any): LoginViewModel {
    return LoginViewModelFromJSONTyped(json, false);
}

export function LoginViewModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginViewModel {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
    };
}

export function LoginViewModelToJSON(json: any): LoginViewModel {
    return LoginViewModelToJSONTyped(json, false);
}

export function LoginViewModelToJSONTyped(value?: LoginViewModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
    };
}

