/* tslint:disable */
/* eslint-disable */
/**
 * API Gateway
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FrequencyValueDTO } from './FrequencyValueDTO';
import {
    FrequencyValueDTOFromJSON,
    FrequencyValueDTOFromJSONTyped,
    FrequencyValueDTOToJSON,
    FrequencyValueDTOToJSONTyped,
} from './FrequencyValueDTO';

/**
 * 
 * @export
 * @interface NotificationDTO
 */
export interface NotificationDTO {
    /**
     * 
     * @type {string}
     * @memberof NotificationDTO
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof NotificationDTO
     */
    nextNotificationTime?: Date;
    /**
     * 
     * @type {FrequencyValueDTO}
     * @memberof NotificationDTO
     */
    frequencyValue?: FrequencyValueDTO;
}

/**
 * Check if a given object implements the NotificationDTO interface.
 */
export function instanceOfNotificationDTO(value: object): value is NotificationDTO {
    return true;
}

export function NotificationDTOFromJSON(json: any): NotificationDTO {
    return NotificationDTOFromJSONTyped(json, false);
}

export function NotificationDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'nextNotificationTime': json['nextNotificationTime'] == null ? undefined : (new Date(json['nextNotificationTime'])),
        'frequencyValue': json['frequencyValue'] == null ? undefined : FrequencyValueDTOFromJSON(json['frequencyValue']),
    };
}

export function NotificationDTOToJSON(json: any): NotificationDTO {
    return NotificationDTOToJSONTyped(json, false);
}

export function NotificationDTOToJSONTyped(value?: NotificationDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'nextNotificationTime': value['nextNotificationTime'] == null ? undefined : ((value['nextNotificationTime']).toISOString()),
        'frequencyValue': FrequencyValueDTOToJSON(value['frequencyValue']),
    };
}

