/* tslint:disable */
/* eslint-disable */
/**
 * API Gateway
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StatusObjectDTO } from './StatusObjectDTO';
import {
    StatusObjectDTOFromJSON,
    StatusObjectDTOFromJSONTyped,
    StatusObjectDTOToJSON,
    StatusObjectDTOToJSONTyped,
} from './StatusObjectDTO';

/**
 * 
 * @export
 * @interface ObjectiveDTO
 */
export interface ObjectiveDTO {
    /**
     * 
     * @type {string}
     * @memberof ObjectiveDTO
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ObjectiveDTO
     */
    definition?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof ObjectiveDTO
     */
    finalDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof ObjectiveDTO
     */
    comment?: string | null;
    /**
     * 
     * @type {StatusObjectDTO}
     * @memberof ObjectiveDTO
     */
    statusObject?: StatusObjectDTO;
}

/**
 * Check if a given object implements the ObjectiveDTO interface.
 */
export function instanceOfObjectiveDTO(value: object): value is ObjectiveDTO {
    return true;
}

export function ObjectiveDTOFromJSON(json: any): ObjectiveDTO {
    return ObjectiveDTOFromJSONTyped(json, false);
}

export function ObjectiveDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ObjectiveDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'definition': json['definition'] == null ? undefined : json['definition'],
        'finalDate': json['finalDate'] == null ? undefined : (new Date(json['finalDate'])),
        'comment': json['comment'] == null ? undefined : json['comment'],
        'statusObject': json['statusObject'] == null ? undefined : StatusObjectDTOFromJSON(json['statusObject']),
    };
}

export function ObjectiveDTOToJSON(json: any): ObjectiveDTO {
    return ObjectiveDTOToJSONTyped(json, false);
}

export function ObjectiveDTOToJSONTyped(value?: ObjectiveDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'definition': value['definition'],
        'finalDate': value['finalDate'] == null ? undefined : ((value['finalDate']).toISOString()),
        'comment': value['comment'],
        'statusObject': StatusObjectDTOToJSON(value['statusObject']),
    };
}

