/* tslint:disable */
/* eslint-disable */
/**
 * ObjectiveManager.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ObjectiveStatus
 */
export interface ObjectiveStatus {
    /**
     * 
     * @type {number}
     * @memberof ObjectiveStatus
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ObjectiveStatus
     */
    name?: string | null;
}

/**
 * Check if a given object implements the ObjectiveStatus interface.
 */
export function instanceOfObjectiveStatus(value: object): value is ObjectiveStatus {
    return true;
}

export function ObjectiveStatusFromJSON(json: any): ObjectiveStatus {
    return ObjectiveStatusFromJSONTyped(json, false);
}

export function ObjectiveStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ObjectiveStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function ObjectiveStatusToJSON(json: any): ObjectiveStatus {
    return ObjectiveStatusToJSONTyped(json, false);
}

export function ObjectiveStatusToJSONTyped(value?: ObjectiveStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

