/* tslint:disable */
/* eslint-disable */
/**
 * API Gateway
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StatusValueDTO
 */
export interface StatusValueDTO {
    /**
     * 
     * @type {number}
     * @memberof StatusValueDTO
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof StatusValueDTO
     */
    name?: string | null;
}

/**
 * Check if a given object implements the StatusValueDTO interface.
 */
export function instanceOfStatusValueDTO(value: object): value is StatusValueDTO {
    return true;
}

export function StatusValueDTOFromJSON(json: any): StatusValueDTO {
    return StatusValueDTOFromJSONTyped(json, false);
}

export function StatusValueDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): StatusValueDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function StatusValueDTOToJSON(json: any): StatusValueDTO {
    return StatusValueDTOToJSONTyped(json, false);
}

export function StatusValueDTOToJSONTyped(value?: StatusValueDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

