/* tslint:disable */
/* eslint-disable */
/**
 * API Gateway
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StatusValueDTO } from './StatusValueDTO';
import {
    StatusValueDTOFromJSON,
    StatusValueDTOFromJSONTyped,
    StatusValueDTOToJSON,
    StatusValueDTOToJSONTyped,
} from './StatusValueDTO';

/**
 * 
 * @export
 * @interface StatusObjectDTO
 */
export interface StatusObjectDTO {
    /**
     * 
     * @type {Date}
     * @memberof StatusObjectDTO
     */
    createdAt?: Date;
    /**
     * 
     * @type {StatusValueDTO}
     * @memberof StatusObjectDTO
     */
    statusValue?: StatusValueDTO;
    /**
     * 
     * @type {string}
     * @memberof StatusObjectDTO
     */
    comment?: string | null;
}

/**
 * Check if a given object implements the StatusObjectDTO interface.
 */
export function instanceOfStatusObjectDTO(value: object): value is StatusObjectDTO {
    return true;
}

export function StatusObjectDTOFromJSON(json: any): StatusObjectDTO {
    return StatusObjectDTOFromJSONTyped(json, false);
}

export function StatusObjectDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): StatusObjectDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'statusValue': json['statusValue'] == null ? undefined : StatusValueDTOFromJSON(json['statusValue']),
        'comment': json['comment'] == null ? undefined : json['comment'],
    };
}

export function StatusObjectDTOToJSON(json: any): StatusObjectDTO {
    return StatusObjectDTOToJSONTyped(json, false);
}

export function StatusObjectDTOToJSONTyped(value?: StatusObjectDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'statusValue': StatusValueDTOToJSON(value['statusValue']),
        'comment': value['comment'],
    };
}

