/* tslint:disable */
/* eslint-disable */
/**
 * API Gateway
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TokenCredentials
 */
export interface TokenCredentials {
    /**
     * 
     * @type {string}
     * @memberof TokenCredentials
     */
    accessToken?: string | null;
}

/**
 * Check if a given object implements the TokenCredentials interface.
 */
export function instanceOfTokenCredentials(value: object): value is TokenCredentials {
    return true;
}

export function TokenCredentialsFromJSON(json: any): TokenCredentials {
    return TokenCredentialsFromJSONTyped(json, false);
}

export function TokenCredentialsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenCredentials {
    if (json == null) {
        return json;
    }
    return {
        
        'accessToken': json['accessToken'] == null ? undefined : json['accessToken'],
    };
}

export function TokenCredentialsToJSON(json: any): TokenCredentials {
    return TokenCredentialsToJSONTyped(json, false);
}

export function TokenCredentialsToJSONTyped(value?: TokenCredentials | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accessToken': value['accessToken'],
    };
}

