/* tslint:disable */
/* eslint-disable */
/**
 * API Gateway
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TokenCredentials } from './TokenCredentials';
import {
    TokenCredentialsFromJSON,
    TokenCredentialsFromJSONTyped,
    TokenCredentialsToJSON,
    TokenCredentialsToJSONTyped,
} from './TokenCredentials';

/**
 * 
 * @export
 * @interface TokenCredentialsResult
 */
export interface TokenCredentialsResult {
    /**
     * 
     * @type {TokenCredentials}
     * @memberof TokenCredentialsResult
     */
    value?: TokenCredentials;
    /**
     * 
     * @type {boolean}
     * @memberof TokenCredentialsResult
     */
    readonly succeeded?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof TokenCredentialsResult
     */
    readonly errors?: Array<string> | null;
}

/**
 * Check if a given object implements the TokenCredentialsResult interface.
 */
export function instanceOfTokenCredentialsResult(value: object): value is TokenCredentialsResult {
    return true;
}

export function TokenCredentialsResultFromJSON(json: any): TokenCredentialsResult {
    return TokenCredentialsResultFromJSONTyped(json, false);
}

export function TokenCredentialsResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenCredentialsResult {
    if (json == null) {
        return json;
    }
    return {
        
        'value': json['value'] == null ? undefined : TokenCredentialsFromJSON(json['value']),
        'succeeded': json['succeeded'] == null ? undefined : json['succeeded'],
        'errors': json['errors'] == null ? undefined : json['errors'],
    };
}

export function TokenCredentialsResultToJSON(json: any): TokenCredentialsResult {
    return TokenCredentialsResultToJSONTyped(json, false);
}

export function TokenCredentialsResultToJSONTyped(value?: Omit<TokenCredentialsResult, 'succeeded'|'errors'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'value': TokenCredentialsToJSON(value['value']),
    };
}

