/* tslint:disable */
/* eslint-disable */
/**
 * API Gateway
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AccountData,
  EditDataDto,
  LoginViewModel,
  RegisterDto,
  Result,
  TokenCredentialsResult,
} from '../models/index';
import {
    AccountDataFromJSON,
    AccountDataToJSON,
    EditDataDtoFromJSON,
    EditDataDtoToJSON,
    LoginViewModelFromJSON,
    LoginViewModelToJSON,
    RegisterDtoFromJSON,
    RegisterDtoToJSON,
    ResultFromJSON,
    ResultToJSON,
    TokenCredentialsResultFromJSON,
    TokenCredentialsResultToJSON,
} from '../models/index';

export interface ApiAccountEditPutRequest {
    editDataDto?: EditDataDto;
}

export interface ApiAccountLoginPostRequest {
    loginViewModel?: LoginViewModel;
}

export interface ApiAccountRegisterPostRequest {
    registerDto?: RegisterDto;
}

export interface ApiAccountUserDataGetRequest {
    userId?: string;
}

/**
 * 
 */
export class AccountApi extends runtime.BaseAPI {

    /**
     */
    async apiAccountEditPutRaw(requestParameters: ApiAccountEditPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Result>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/Account/edit`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: EditDataDtoToJSON(requestParameters['editDataDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResultFromJSON(jsonValue));
    }

    /**
     */
    async apiAccountEditPut(requestParameters: ApiAccountEditPutRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Result> {
        const response = await this.apiAccountEditPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiAccountLoginPostRaw(requestParameters: ApiAccountLoginPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TokenCredentialsResult>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/Account/login`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LoginViewModelToJSON(requestParameters['loginViewModel']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TokenCredentialsResultFromJSON(jsonValue));
    }

    /**
     */
    async apiAccountLoginPost(requestParameters: ApiAccountLoginPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TokenCredentialsResult> {
        const response = await this.apiAccountLoginPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiAccountRefreshTokenGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TokenCredentialsResult>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/Account/refreshToken`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TokenCredentialsResultFromJSON(jsonValue));
    }

    /**
     */
    async apiAccountRefreshTokenGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TokenCredentialsResult> {
        const response = await this.apiAccountRefreshTokenGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async apiAccountRegisterPostRaw(requestParameters: ApiAccountRegisterPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TokenCredentialsResult>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/Account/register`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RegisterDtoToJSON(requestParameters['registerDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TokenCredentialsResultFromJSON(jsonValue));
    }

    /**
     */
    async apiAccountRegisterPost(requestParameters: ApiAccountRegisterPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TokenCredentialsResult> {
        const response = await this.apiAccountRegisterPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiAccountUserDataGetRaw(requestParameters: ApiAccountUserDataGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountData>> {
        const queryParameters: any = {};

        if (requestParameters['userId'] != null) {
            queryParameters['userId'] = requestParameters['userId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/Account/userData`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountDataFromJSON(jsonValue));
    }

    /**
     */
    async apiAccountUserDataGet(requestParameters: ApiAccountUserDataGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountData> {
        const response = await this.apiAccountUserDataGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
