/* tslint:disable */
/* eslint-disable */
/**
 * API Gateway
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  FrequencyValueDTO,
} from '../models/index';
import {
    FrequencyValueDTOFromJSON,
    FrequencyValueDTOToJSON,
} from '../models/index';

/**
 * 
 */
export class FrequencyApi extends runtime.BaseAPI {

    /**
     */
    async apiFrequencyAllGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<FrequencyValueDTO>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/Frequency/all`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(FrequencyValueDTOFromJSON));
    }

    /**
     */
    async apiFrequencyAllGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<FrequencyValueDTO>> {
        const response = await this.apiFrequencyAllGetRaw(initOverrides);
        return await response.value();
    }

}
