/* tslint:disable */
/* eslint-disable */
/**
 * ObjectiveManager.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ObjectiveStatus,
} from '../models/index';
import {
    ObjectiveStatusFromJSON,
    ObjectiveStatusToJSON,
} from '../models/index';

/**
 * 
 */
export class StatusesApi extends runtime.BaseAPI {

    /**
     */
    async statusesAllGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ObjectiveStatus>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/Statuses/all`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ObjectiveStatusFromJSON));
    }

    /**
     */
    async statusesAllGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ObjectiveStatus>> {
        const response = await this.statusesAllGetRaw(initOverrides);
        return await response.value();
    }

}
